import { Roboto } from 'next/font/google'
import './globals.css'

const Roboto_Mono = Roboto({ weight: '400', subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={Roboto_Mono.className}>{children}</body>
        </html>
    )
}
